__version__ = "0.0.1"
__url__ = "https://github.com/bekzatalish/zero-ml"
__description__ = "Machine learning algorithms implemented from scratch using Python and NumPy."
__author__ = "Bekzat Alish"
__email__ = "bekzatalish@gmail.com"
